version: '3'

# services:
#   e-commerce-app:
#     image: piaowei/e-commerce-gigalogy:latest
#     build:
#       context: .
#       dockerfile: Dockerfile # Replace with your actual Dockerfile name if different
#     ports:
#       - '5173:5173' # Map the host port 8080 to the internal container port 5173
#     environment:
#       - NODE_ENV=production

services:
  e-commerce-app:
    build: .
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
